select b.TITLE AS TITLE, b.BOARD_ID AS BOARD_ID, r.REPLY_ID AS REPLY_ID,
r.WRITER_ID AS WRITER_ID, r.CONTENTS AS CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
from USED_GOODS_BOARD b
join USED_GOODS_REPLY r on b.BOARD_ID = r.BOARD_ID
where b.CREATED_DATE like '2022-10%'
order by r.CREATED_DATE ASC, b.TITLE ASC;